// Auth
import { LOGIN_SCHEMA, GET_CURRENT_USER } from "./auth.js";

export {LOGIN_SCHEMA, GET_CURRENT_USER}


// User
import { GET_ALL_USERS_SCHEMA, GET_USER_SCHEMA, CREATE_USER_SCHEMA, UPDATE_USER_SCHEMA, DELETE_USER_SCHEMA } from "./user.ts";

export { GET_ALL_USERS_SCHEMA, GET_USER_SCHEMA, CREATE_USER_SCHEMA, UPDATE_USER_SCHEMA, DELETE_USER_SCHEMA}