// Auth
import { LOGIN_SCHEMA, GET_CURRENT_USER } from "./authSchemas.js";

export {LOGIN_SCHEMA, GET_CURRENT_USER}


// User
import { GET_ALL_USERS_SCHEMA, GET_USER_SCHEMA, CREATE_USER_SCHEMA, UPDATE_USER_SCHEMA, DELETE_USER_SCHEMA } from "./userSchemas.js";

export { GET_ALL_USERS_SCHEMA, GET_USER_SCHEMA, CREATE_USER_SCHEMA, UPDATE_USER_SCHEMA, DELETE_USER_SCHEMA}

// Products
import { CREATE_PRODUCT_SCHEMA, UPDATE_PRODUCT_SCHEMA, GET_PRODUCTS_SCHEMA, GET_PRODUCT_SCHEMA, DELETE_PRODUCT_SCHEMA } from "./productSchemas.js";

export { CREATE_PRODUCT_SCHEMA, UPDATE_PRODUCT_SCHEMA, GET_PRODUCTS_SCHEMA, GET_PRODUCT_SCHEMA, DELETE_PRODUCT_SCHEMA }